# Generated by Django 4.1.5 on 2023-02-06 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StreamModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stream_id', models.IntegerField(unique=True, verbose_name='配信id')),
                ('title', models.CharField(max_length=100, verbose_name='配信タイトル')),
                ('streamer_id', models.CharField(max_length=100, verbose_name='配信者id')),
                ('streamer', models.CharField(max_length=100, verbose_name='配信者')),
                ('streamer_name', models.CharField(max_length=100, verbose_name='配信者名')),
                ('game_name', models.CharField(max_length=100, verbose_name='ゲーム名')),
                ('starttime', models.DateTimeField()),
                ('type', models.CharField(default='offline', max_length=100, verbose_name='状態')),
            ],
            options={
                'verbose_name_plural': 'Board',
            },
        ),
    ]
