# Generated by Django 4.1.5 on 2023-02-12 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StreamerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('streamer_id', models.IntegerField(unique=True, verbose_name='配信者id')),
                ('streamer', models.CharField(max_length=100, verbose_name='配信者')),
                ('streamer_name', models.CharField(max_length=100, verbose_name='配信者名')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(default='offline', max_length=100, verbose_name='状態')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'verbose_name_plural': 'ストリーマー',
            },
        ),
        migrations.CreateModel(
            name='StreamModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stream_id', models.IntegerField(unique=True, verbose_name='配信id')),
                ('title', models.CharField(max_length=100, verbose_name='配信タイトル')),
                ('streamer_id', models.IntegerField(verbose_name='配信者id')),
                ('streamer', models.CharField(max_length=100, verbose_name='配信者')),
                ('streamer_name', models.CharField(max_length=100, verbose_name='配信者名')),
                ('game_name', models.CharField(max_length=100, verbose_name='ゲーム名')),
                ('starttime', models.DateTimeField()),
                ('type', models.CharField(default='offline', max_length=100, verbose_name='状態')),
                ('viewer_count', models.IntegerField(default=0, verbose_name='視聴者数')),
            ],
            options={
                'verbose_name_plural': 'Board',
            },
        ),
    ]
