# Generated by Django 4.1.5 on 2023-02-02 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streammodel',
            name='stream_id',
            field=models.IntegerField(unique=True, verbose_name='配信id'),
        ),
    ]
