# Generated by Django 4.1.5 on 2023-02-13 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_alter_commentmodel_stream_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentmodel',
            name='id_for_stream',
            field=models.IntegerField(blank=True, null=True, verbose_name='配信毎のid'),
        ),
    ]
