# Generated by Django 4.1.5 on 2023-02-14 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_commentmodel_id_for_stream'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamermodel',
            name='channel',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='チャンネルURL'),
        ),
    ]
