# Generated by Django 4.1.5 on 2023-02-16 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_streammodel_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='streammodel',
            name='comment_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='コメント数'),
        ),
    ]
