# Generated by Django 4.1.5 on 2023-02-16 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0007_streammodel_comment_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streammodel',
            name='comment_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='コメント数'),
        ),
    ]
