# Generated by Django 4.1.5 on 2023-01-17 14:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nippo', '0002_alter_nippomodel_options_alter_nippomodel_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nippomodel',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
