# Generated by Django 4.1.5 on 2023-02-05 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='aaa', max_length=100, unique=True, verbose_name='ユーザー名'),
        ),
    ]
