# Generated by Django 4.1.5 on 2023-02-05 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_profile_username_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default=False, max_length=100, unique=True, verbose_name='ユーザー名'),
        ),
    ]
