# Generated by Django 4.1.5 on 2023-02-05 13:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default=uuid.uuid1, max_length=100, unique=True, verbose_name='ユーザー名'),
        ),
    ]
