# Generated by Django 4.1.5 on 2023-02-05 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default=False, max_length=255, verbose_name='Eメールアドレス'),
        ),
    ]
